sudo: true
language: c++
dist: trusty 
install:
    # python 3
   - sudo apt install python3
   - python3 -m venv .venv3 
   - source .venv3/bin/activate && \ 
     pip install --upgrade pip && \
     pip install -r requirements_3_5.txt && \
     pip install conan
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
env:
   global:
     - CONAN_REFERENCE: "cpp14-basic/1.0.0"
     - CONAN_USERNAME: "user"
     - CONAN_LOGIN_USERNAME: "user"
     - CONAN_CHANNEL: "testings"
 
compiler:
  - gcc
  - clang  
env:
  matrix:
    - BUILD_TYPE=debug   VERBOSE_MAKE=true
    - BUILD_TYPE=   VERBOSE_MAKE=true
matrix:
  allow_failures:
    - env BUILD_TYPE=debug
notifications:
  email: false  
git:
  submodules: false
  depth: 3
branches:
  except: 
    - gh-pages
script:
  - chmod +x .travis/run.sh && ./.travis/run.sh
  - cd build
   - source .venv3/bin/activate && \ 
     conan install .. && \
     conan install .. --build googletest && \
     conan install .. --build Boost && \
     conan install ..  --build gmock && \
     cd .. && \
     cmake -rf . && \
     make   
  - ./bin/cpp14_basics
  - echo $?
  - ./bin/cpp14_basics_test 
  - echo $?
