language: c++
install:
  - apt-get update && apt-get install cmake -y && cmake --version
compiler:
  - gcc
  - clang
env:
  - DEBUG=
  - DEBUG=debug
script: 
  - cmake -rf .
  - cmake . -DBUILD_SHARED_LIBS=ON
  - make 
