language: c++
sudo: required
dist: trusty 
sudo: require
install:
  - sudo apt-get install libgtest-dev -y
  #- sudo cd /usr/src/googletest && sudo cmake -rf . && sudo cmake . -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON 
  #- sudo make && sudo make install
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - cmake
compiler:
  - gcc
  - clang
env:
  - DEBUG=
  - DEBUG=debug
script: 
   #- sudo dkpg -L libgtest-dev
   - git clone -b github https://github.com/martibayoalemany/cpp14-basics.git 
   - cd cpp14-basics && sudo cp lib/* /usr/local/lib/
   - cmake . && make
   - docker build docker
