sudo: true
language: c++
dist: trusty 
sudo: require
install:
   sudo apt-get -f install libboost-all-dev libgtest-dev
   pip install conan
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - cmake
   - libgtest-dev
compiler:
  - clang
  #- gcc
env:
  matrix:
    - VERBOSE_MAKE=true
    - BUILD_TYPE=debug   VERBOSE_MAKE=true
notifications:
  email: false  
git:
  submodules: false
script:
   #- if which gcc; then `which gcc` -v; fi
   - cd build
   - conan install .. 
   - conan install .. --build llvm
   - cd ..
   - cmake -rf .
   - make
   # TODO: Fix the segmentation fault with gcc
   - ./bin/cpp14_basics
   - echo $?
   #- [ -e ./bin/cpp14_basics_test ] && ./bin/cpp14_basics_test || echo "cpp14_basics_test no found" 
   #- echo $?
