language: c++
sudo: required
dist: trusty 
sudo: require
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - cmake
compiler:
  - gcc
  - clang
env:
  - DEBUG=
  - DEBUG=debug
script: 
  #---> Installing google test from github
  # git clone https://github.com/google/googletest.git 
  # pushd .
  # cd googletest 
  # cmake .
  # make
  # sudo -s make install
  # popd 
  #---> Installing google test from tar.gz
  - wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz 
  - tar xvfz release-1.7.0.tar.gz 
  - pushd .
  - cd googletest-release-1.7.0 
  - cd googletest
  - cmake .
  - make
  - sudo -s make install
  - popd
  #---> Installing google test with apt-get
  #- sudo -s apt-get install libgtest-dev -	
  - gcc -v && g++ -v && cmake --version
  - cmake . 
  - cmake . -DBUILD_SHARED_LIBS=ON 
  - make 
  - make clean
