language: c++
sudo: required
dist: trusty 
sudo: require
install:
  - sudo apt-get install libgtest-dev -y
  - cd /usr/src/googletest && cmake -rf . && cmake . -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON 
  - make && make install
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - cmake
compiler:
  - gcc
  - clang
env:
  - DEBUG=
  - DEBUG=debug
script: 
   - git clone -b github https://github.com/martibayoalemany/cpp14-basics.git 
   - cd cpp14-basics && cmake . && make
   - docker build docker
