language: c++
sudo: required
dist: trusty 
sudo: require
install:
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - cmake
compiler:
  - clang
  - gcc
env:
  matrix:
    - VERBOSE_MAKE=true
    - BUILD_TYPE=debug   VERBOSE_MAKE=true
notifications:
  email: false  
script: 
   - git clone -b github https://github.com/martibayoalemany/cpp14-basics.git 
   - cd cpp14-basics 
   - ./scripts/init_modules.sh
   - cmake -rf .
   - make
