language: c++
sudo: required
dist: trusty 
sudo: require
install:
  - sudo apt-get install libgtest-dev
 # Download docker over http in case apt does not work
  - wget https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.03.0~ce-0~ubuntu-xenial_amd64.deb
  - sudo dpkg -i docker-ce_17.03.0~ce-0~ubuntu-xenial_amd64.deb
  - sudo docker run hello-world
  - lsb_release -a
  # Allows apt over HTTPS
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
  # Docker official key
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - echo "is 9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88. ?"
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
  - sudo apt-get update
  - sudo apt-cache madison docker-ce
  #- sudo apt-get install docker-ce
  #- sudo docker run hello-world
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - cmake
compiler:
  - gcc
  - clang
env:
  - DEBUG=
  - DEBUG=debug
script: 
  #---> Installing google test from github
  # git clone https://github.com/google/googletest.git 
  # pushd .
  # cd googletest 
  # cmake .
  # make
  # sudo -s make install
  # popd 
   - docker build docker
   - cat /home/travis/.travis/job_stages
   - ls /home/travis/
   - ls /home/travis/.travis
  # ---> Installing google test from tar.gz
  # - wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz 
  # - tar xvfz release-1.7.0.tar.gz 
  # - pushd .
  # - cd googletest-release-1.7.0 
  # - cmake .
  # - make
  # - sudo -s cp libgtest_main.so /usr/local/lib
  # - sudo -s cp libgtest.so /usr/local/lib 
  # - pwd
  # - sudo -s make install
  # - popd
  # ---> Installing google test with apt-get
  # - cmake . 
  # - cmake . -DBUILD_SHARED_LIBS=ON 
  # - make 
  # - make clean
