language: c++
sudo: required
dist: trusty 
sudo: require
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - cmake
compiler:
  - gcc
  - clang
env:
  - DEBUG=
  - DEBUG=debug
script:    
   - git clone -b github https://github.com/martibayoalemany/cpp14-basics.git 
   - cd cpp14-basics    
   - cmake . 
   - make   