language: c++
sudo: required
dist: trusty 
sudo: require
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - cmake
compiler:
  - gcc
  - clang
env:
  - DEBUG=
  - DEBUG=debug
script: 
  - cmake -rf 
  - cmake . -DBUILD_SHARED_LIBS=ON
  - make
