sudo: true
language: c++
dist: trusty 
sudo: require
install:
   sudo apt-get -f install libboost-all-dev libgtest-dev
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - cmake
   - libgtest-dev
compiler:
  - clang
  - gcc
env:
  matrix:
    - VERBOSE_MAKE=true
    - BUILD_TYPE=debug   VERBOSE_MAKE=true
notifications:
  email: false  
git:
  submodules: false
script:
   - cmake -rf .
   - make
